### ISSUE TITLE
根目录的 "Scraper" 这个编译后的二进制文件，是否可以删除？

### ISSUE THREAD

**Issue by menduo** [yangwenmai/github-trending-backup#2]
<img width="1157" alt="图片" src="https://user-images.githubusercontent.com/13566062/88250658-cfd4fb80-ccda-11ea-9e3e-00a7a13f7ad3.png">

因为前两天我修改 repo url #1 后发现并没有真正生效，才看到是因为用的仍然是旧的已编译的文件。我有想编译一个push上来，但又想：

1、这个 Scrape 是哪个平台的？Linux、macOS？

2、是不是可以不要将这个文件加到仓库里？

3、定时任务是在 heroku 执行还是？heroku 的话，那应该就是 linux 了。

还有没有其他改进方式呢？

**Comment by yangwenmai** [comment]
我改一下，谢谢你提出来。
